apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Chart.Name }}-route
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-route
  annotations:
    haproxy.router.openshift.io/timeout: "300s"
    haproxy.router.openshift.io/disable_cookies: "true"
    haproxy.router.openshift.io/balance: "roundrobin"
spec:
  host: {{ .Values.fqdn }}
  path: {{ .Values.path }}
  to:
    kind: Service
    name: {{ .Chart.Name }}-service
  port:
    targetPort: {{ .Values.port }}