spring:
  mvc:
    servlet:
      path: /backend
  datasource:
    url: jdbc:postgresql://postgres:5432/todo_list
    username: program
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate