apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.name }}:{{ .Values.image.version }}
          imagePullPolicy: Always
          env:
            - name: REACT_APP_BACKEND_IP
              value: http://{{ .Values.fqdn }}/backened
          ports:
            - name: web
              containerPort: {{ .Values.port }}